### ISSUE TITLE
limitReachedWithTokenBucketTTL probably useless with x/time/rate burst == 1

### ISSUE THREAD

**Issue by zwopir** [didip/tollbooth#53] opened 2017-11-03 11:29 UTC
since #52 the private function `func (l *Limiter) limitReachedWithTokenBucketTTL(key string, tokenBucketTTL time.Duration) bool` and thus the tokenBucketTTL functionality doesn't make sense anymore:
The burst parameter `b` in x/time/rate `NewLimiter` is used as max burst *and* initial bucket size (see comment in https://godoc.org/golang.org/x/time/rate#Limiter and https://github.com/golang/time/blob/master/rate/rate.go#L346).
So a first request to a new (re)created bucket is always granted. Because of the initial bucket size of one, a second request is only granted, if the time elapsed (d) fullfills `1/d < r` with r being the bucket refill rate - in tollbooth case `rate.Limit(lmtMax)`.

So a bucket ttl only slighly increases the max rate, which is neglectable for 1/ttl << r.

Does it make sense to introduce an initial bucket size to the `ExpirableOptions` struct and use it if the ttl is not set to the default value? I'll happily prepare a PR if all of the above makes sense.

**Comment by davis12529** [comment] 2017-11-08 17:18
Yes #52 introduced another (more serious) bug with rate limiting behaviour.

Burst size, b should not be 1 at https://github.com/didip/tollbooth/blob/170b8fa2ab876c0a9999fa8422fcdd32a0b213c4/limiter/limiter.go#L432. 

I think it was set to 1 assuming that each call to `Allow()` will only consume 1 token (at time.Now()). 

However I find that this is not the case. In my quick test where m config is `limiter := tollbooth.NewLimiter(500, nil)` (expecting at most 500 request/s). I ran `ab -k -c 5 -n 5 "$ENDPOINT" and I get four 429's and one 200.

Instead of 
`rate.NewLimiter(rate.Limit(lmtMax), 1),`
it should be
`rate.NewLimiter(rate.Limit(lmtMax), int(lmtMax)),`

**Comment by zwopir** [comment] 2017-11-08 17:28
not exacly: the burst rate `b` in  the `rate.NewLimiter` constructor is used as 
 - burst rate
 - initial bucket size
For the burst rate, using b=1 is ok, as the call to `Allow()` happens atomically to check if the current request can be performed. If you want to support a "bursty" request profile, you can do this by creating a newly filled bucket every ttl seconds.

You get 1x200 plus 4x429 because ab creates request at a rate far faster than 500 requests/sec.

**Comment by tylerb** [comment] 2017-11-08 18:10
@zwopir I am not sure I entirely understand the issue you are seeing. Am I correct in thinking that the issue you're seeing only occurs in the event of a bucket expiring and being recreated?

To be honest, I'm not entirely sure what the point of the tokenBucketTTL is in the first place. What problem is it trying to solve? More specifically, @zwopir, what problem are you trying to solve by using it?

@davis12529 I believe @zwopir is correct in that you are hitting the server far more quickly than 500 req/sec. That will definitely cause it to fail. I experienced this same issue with the old tests. They had been passing, previously, because the initial bucket size was 1000, so of course it could fulfill the initial 1000 requests. After fixing the usage of the token bucket, the tests failed immediately, as they were expecting to get 1000 tokens in micro|milliseconds in a loop.

I fixed the tests by adding an appropriate sleep between each request. 

See https://github.com/didip/tollbooth/pull/52/commits/954c508241a3b69d4ca1958240c1037604bd8a0f

**Comment by davis12529** [comment] 2017-11-08 19:21
Thank you @zwopir @tylerb for clarification. I get it now. I went back and increased `r` until a concurrent connections of 2 by `ab` did not trigger the limit. I take my word back on `b` should not be 1 (assuming no support for burst)

I guess for the config`tollbooth.NewLimiter(500, nil)`, 500 req/sec is actually 500/1e^9 req/nanosecond. 

I am actually new to rate limiting, hence I thought the unit precision was time.Second. Perhaps it could be clearer that the unit time for is actually time.Nanosecond (figured out from `durationFromTokens` and `tokensFromDuration` https://github.com/golang/time/blob/master/rate/rate.go#L371), unless that is a standard convention.

**Comment by zwopir** [comment] 2017-11-09 09:43
@tylerb my issue is that we were using buckets with a ttl and an initial bucket fill to support a request rate distribution that is very spiky. That was supported "accidently" before correcting the usage of `rate.NewLimiter` to `b=1`. If the initial bucket size is reduced to 1, it doesn't make sense to recreate the limiter every ttl seconds, because

I think the point of tokenBucketTTL at first place is to reset the rate limiting state (i.e. the amount of tokens in the bucket). That could be decrease it ( = set to b), if not all buckets were consumed  or increase it to `b`. In my use case it was an increase.

**Comment by didip** [comment] 2017-11-09 17:04
Sorry that I have not been active in the convo, work has been really busy recently.

I will try to take a look at these issues this weekend. But looks like there’s good conversations going.

**Comment by tylerb** [comment] 2017-11-09 18:51
@davis12529 thanks for the discussion. It's been very helpful.

@zwopir to be honest, it kind of feels like the TTL for the limiter was added as a band-aid over the issue fixed in #52. I don't see any reason to reset the limiter using a TTL at all. The previous functionality would define a bucket of size `n` and then refill it as a rate of `tokenTTL` every second. 

For example, I was doing `20,1`, which gave me 20 tokens initially, refilled at a rate of 1 per second. As such, anything over 1req/sec would eventually exhaust the bucket. TTL would "fix" this by forcibly refilling the bucket every TTL seconds.

I actually feel like the TTL system could be completely removed in favor of allowing the `burst` value to be modified. Spikey traffic patterns could be easily handled by having a high burst value and refill rate.

@didip this would be a pretty significant change, were we to move forward with it. I think it would be best, but I also may be misunderstanding the purpose of the limiter TTL. However, removing limiter TTL in favor of burst would significantly simplify the code and usage of the package.

**Comment by zwopir** [comment] 2017-11-09 18:57
not exactly: we never use `AllowN`, only `Allow()` in tollbooth. So the x/time/burst library never sees a burst.

**Comment by tylerb** [comment] 2017-11-09 20:47
@zwopir agreed that we never use `AllowN`. However, `AllowN` basically says "can I get `N` tokens at this particular nanosecond?"

As such, multiple requests that are nanoseconds apart effectively act like a "burst". That was an issue I had to fix in the tests when I submitted my PR. Of course, my understanding of it could be incorrect. I do see that the burst value is used for checking if the `n` requested is less than burst, but it's also used as the token bucket size, which seems to be more important in this case.

Perhaps I'm misunderstanding your particular issue.

**Comment by didip** [comment] 2017-11-13 02:45
I think I see what @zwopir is confused about.

`TokenBucketExpirationTTL` has nothing to do with the actual rate-limiter feature (I know, this project has multiple TTLs, confusing people).

Each rate-limiter is actually a key-value pair, so I keep track of them in a hashmap. In the past, some users complained that the hashmap keep growing unbounded.

So, in `v2.x.x`, expirable hashmap is used.

On side note, I appreciate @tylerb explaining what is going on under the hood with rate-limiter. Previously, we had used juju's rate limiter where we could actually configure the duration of the limiter.

**Comment by zwopir** [comment] 2017-11-13 13:50
so the expiring hashmap was only meant to prevent the map from growing unboundedly? 

It had the side effect, that every ttl seconds the bucket was refilled and thus granted a few requests over the configured rate every time the bucket was recreated in the expiring map. So with expiring buckets and an initial bucket size `b>1` (pre #52) it was possible to support "bursty" requests.

Would it make sense to optionally reintroduce such a behavior?

**Comment by tylerb** [comment] 2017-11-13 17:09
THAT makes sense. I hadn't even considered that. So it's to make sure we clean up after ourselves and don't leave limiters just hanging around. That makes a lot more sense. Using it as a some kind of "reset" for the bucket seemed very odd to me. I still feel like configurable burst size would allow for handling of bursty requests. If you're resetting the bucket all the time anyway, I'm not sure what the point of a limiter is?

**Comment by zwopir** [comment] 2017-11-13 17:44
guys, you are right. I though that multiple fast consecutive calls to the `Allow()` function don't form a "proper" burst. But they do (just tested with a few simple lines).

So simply passing a burst rate parameter would perfectly fit the burst use case.

**Comment by didip** [comment] 2017-11-13 17:58
@zwopir Correct, the expiring hashmap was only meant to prevent the map from growing unboundedly.

@zwopir @tylerb I think having a configurable burst size is a good idea, won't be too hard to implement and we can set the default to 1 so that it is backward compatible with `v3.x.x`.

**Comment by zwopir** [comment] 2017-11-13 17:59
great, thanks for clarification. I just cloned your project to provide a PR

**Comment by tylerb** [comment] 2017-11-13 18:01
@didip Having the burst size at 1, currently, is incorrect and leads to unexpected behavior. I hadn't considered all the implications of setting it to 1. There is a lot of previous discussion around this.

I strongly feel that we should set burst to the number of requests per second, by default, and allow it to be configured after that if necessary.

**Comment by didip** [comment] 2017-11-13 18:03
@tylerb I see. I seemed to remember that older version of Tollbooth used max requests as burst size in the past. I am surprised that all tests still passed.

@zwopir Thanks! Just create a setter & getter with a lock (just like other properties). See @tylerb comment above, could you set the default to be the `GetMax()` value?

**Comment by zwopir** [comment] 2017-11-13 18:04
yes, will do

**Comment by didip** [comment] 2017-11-13 18:05
@zwopir If you could ensure that `go test ./...` still works, that would be super appreciated.

**Comment by tylerb** [comment] 2017-11-13 18:06
@didip having the max requests as the burst size caused it to behave nicely for the first round of requests, but then it would fail as the refill rate was far lower than expected. I had to update some of the tests to account for the burst size being set to 1.

**Comment by didip** [comment] 2017-11-13 18:09
@tylerb Gotcha. Who would have thought that there are so many corner cases for a supposedly simple project. :)

**Comment by didip** [comment] 2017-11-13 18:10
@zwopir If tests failed, they may have to be updated to `SetBurstSize(1)` since @tylerb was specifically testing for burst size == 1.

**Comment by zwopir** [comment] 2017-11-13 18:13
ok.

the burst rate `b`in golang.org/x/time/rate is an int, while `max` is an int64. What type conversion would you propose?

**Comment by didip** [comment] 2017-11-13 18:15
@zwopir Just down cast it :) `int(GetMax())`

**Comment by zwopir** [comment] 2017-11-13 18:16
yes, if you have burst sizes exceeding `int`s you screwed anyways ;)

**Closed** 2017-11-18 22:33 UTC

**Comment by didip** [comment] 2017-11-18 22:36
I have released `v3.0.1` for this fix.

**Comment by zwopir** [comment] 2017-11-20 06:40
Thanks for the release and the discussion!
